// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `openanolis_users` table.
    ///
    /// (Automatically generated by Diesel.)
    openanolis_users (id) {
        /// The `id` column of the `openanolis_users` table.
        ///
        /// Its SQL type is `Bigint`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Bigint,
        /// The `userno` column of the `openanolis_users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        userno -> Text,
        /// The `username` column of the `openanolis_users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        username -> Text,
        /// The `email` column of the `openanolis_users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Text,
        /// The `aas_auth_key` column of the `openanolis_users` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        aas_auth_key -> Nullable<Text>,
        /// The `aas_instance` column of the `openanolis_users` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        aas_instance -> Bool,
        /// The `insert_time` column of the `openanolis_users` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        insert_time -> Timestamp,
    }
}
